name = "103-ntm-space"
author = "103"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aebfe55358d7a4b34c3e713c3f48b74e208797d38fee64ad9d2beaa351bb9eb1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
