REWARD_MODIFIER = 1

INTRO = {
    # Modpack Introduction
    "AdditionalModpac-KB3dBT-nRp6btinFrnJXkg==.json": 1 * REWARD_MODIFIER,
    "AdditionalNTMMod--haXUJ5EQD-cNU0TZtxV0g==.json": 1 * REWARD_MODIFIER,
    "BackpacksandExpl-ThViNfMEQC2vMD1tN0F4rg==.json": 2 * REWARD_MODIFIER,
    "BetterQuesting-yAANgk0sR0WzEjsNHwpfPA==.json": 1 * REWARD_MODIFIER,
    "InventoryManagem-dSSo1iITRNiencxnP_dGQw==.json": 1 * REWARD_MODIFIER,
    "ModpackIntroduct-3G7SDsaNR4a8CT-MMOFJgg==.json": 256 * REWARD_MODIFIER, # initial injection
    "NaturesCompass-TCSwirb4QWe9becAfFkylw==.json": 2 * REWARD_MODIFIER,
    "OffHand-_hMHErY_R-2HhEWC8iOYUA==.json": 1 * REWARD_MODIFIER,
}

NTM_EARLY = {
    # NTM: Early Game
    "AdditionalFluidT-9RM80ygPQTaxxeDb0-qGtw==.json": 3 * REWARD_MODIFIER,
    "AdvancedEnchantm-fmoLTwZ4QemPTJ_pyh1YtA==.json": 6 * REWARD_MODIFIER,
    "AirIntake-bC_DUDpuRDy7Y0vktb-pdQ==.json": 4 * REWARD_MODIFIER,
    "AmmoPressandGuns-AAAAAAAAAAAAAAAAAAAAaA==.json": 5 * REWARD_MODIFIER,
    "AnalogCircuitBoa-AAAAAAAAAAAAAAAAAAAAFA==.json": 5 * REWARD_MODIFIER,
    "Anvil-AAAAAAAAAAAAAAAAAAAAAw==.json": 3 * REWARD_MODIFIER,
    "ArcWelder-AAAAAAAAAAAAAAAAAAAAHw==.json": 5 * REWARD_MODIFIER,
    "ArmorModificatio-3J7vD46NQg6IMMDRALpT-A==.json": 4 * REWARD_MODIFIER,
    "AssemblyMachine-AAAAAAAAAAAAAAAAAAAAGQ==.json": 6 * REWARD_MODIFIER,
    "AutomaticBuzzSaw-AAAAAAAAAAAAAAAAAAAA0A==.json": 5 * REWARD_MODIFIER,
    "AutomaticThreshe-kfQnj5gZSnGUxUmB2HCnJg==.json": 5 * REWARD_MODIFIER,
    "BetterFurnaces-gKQiP_zES4KokMmon9bDQg==.json": 4 * REWARD_MODIFIER,
    "BlastFurnace-AAAAAAAAAAAAAAAAAAAACQ==.json": 6 * REWARD_MODIFIER,
    "Bobmazon-IAP1AGA2TV-TtMAv_QMrIA==.json": 2 * REWARD_MODIFIER,
    "BoilerandSteamCo-AAAAAAAAAAAAAAAAAAAAVQ==.json": 6 * REWARD_MODIFIER,
    "BurnerPress-AAAAAAAAAAAAAAAAAAAABA==.json": 4 * REWARD_MODIFIER,
    "CharcoalAutomati-bCeMQCbfSO6qNCtsy9NcnA==.json": 3 * REWARD_MODIFIER,
    "ChargingStation-GgjbEvl7T9OF7WnmHdgMNA==.json": 4 * REWARD_MODIFIER,
    "CharmofProtectio-D0bv2vfWSkK1soyqHDwqjQ==.json": 4 * REWARD_MODIFIER,
    "ChemicalPlant-AAAAAAAAAAAAAAAAAAAAIg==.json": 6 * REWARD_MODIFIER,
    "Cladding-UKkcpXk3SEWHXLIVC5VTDg==.json": 3 * REWARD_MODIFIER,
    "CombinationOven-AAAAAAAAAAAAAAAAAAAAIQ==.json": 5 * REWARD_MODIFIER,
    "Compressor-jcaOirN6QCOC50YJbil2rQ==.json": 6 * REWARD_MODIFIER,
    "ConveyorBelt-AAAAAAAAAAAAAAAAAAAAKg==.json": 4 * REWARD_MODIFIER,
    "Crucible-AAAAAAAAAAAAAAAAAAAAHQ==.json": 6 * REWARD_MODIFIER,
    "DrainagePipe-AAAAAAAAAAAAAAAAAAABdg==.json": 4 * REWARD_MODIFIER,
    "EnergyCables-AAAAAAAAAAAAAAAAAAAAEQ==.json": 3 * REWARD_MODIFIER,
    "EnergyStorage-zinQBRxTQ5OaRyf9vxYaEg==.json": 3 * REWARD_MODIFIER,
    "Glyphids-AAAAAAAAAAAAAAAAAAAABQ==.json": 2 * REWARD_MODIFIER,
    "HazmatSuits-AAAAAAAAAAAAAAAAAAAADw==.json": 4 * REWARD_MODIFIER,
    "HeatingOvenFireb-cUWyKdzATTSYaMg1MxZqYw==.json": 4 * REWARD_MODIFIER,
    "HEtoRFConverter-JcBabPI8RzGGmai3SwlcLw==.json": 5 * REWARD_MODIFIER,
    "HighSpeedSteel-AAAAAAAAAAAAAAAAAAAAJQ==.json": 6 * REWARD_MODIFIER,
    "IndustrialMixer-AAAAAAAAAAAAAAAAAAAA0w==.json": 6 * REWARD_MODIFIER,
    "Latex-JzWhzfD0T2mxYD1NrT9b6A==.json": 3 * REWARD_MODIFIER,
    "LongDistanceEner-s8lSFTDKSpqK44PLhdfusw==.json": 5 * REWARD_MODIFIER,
    "MachineUpgradeTe-AAAAAAAAAAAAAAAAAAABSA==.json": 4 * REWARD_MODIFIER,
    "MiningCharge-AAAAAAAAAAAAAAAAAAAAhQ==.json": 4 * REWARD_MODIFIER,
    "MultiFluidIdenti-M3mauW7uTCej4mql-Wnhqg==.json": 2 * REWARD_MODIFIER,
    "NTMIntroduction-AAAAAAAAAAAAAAAAAAAAAQ==.json": 1 * REWARD_MODIFIER,
    "OilResevoirDetec-AAAAAAAAAAAAAAAAAAAAJg==.json": 4 * REWARD_MODIFIER,
    "PackingTape-RBJS7D2ATpq7GUingAewuQ==.json": 2 * REWARD_MODIFIER,
    "PipeAnchors-jOGBJWaqQxepkxcY_MRqFA==.json": 2 * REWARD_MODIFIER,
    "PlayerDecontamin-AAAAAAAAAAAAAAAAAAABCw==.json": 5 * REWARD_MODIFIER,
    "PneumaticPipes-pTXtLJnPRu6lyiOqGVP7lw==.json": 4 * REWARD_MODIFIER,
    "PollutionDetecto-AAAAAAAAAAAAAAAAAAAAEg==.json": 4 * REWARD_MODIFIER,
    "RotaryFurnace-AAAAAAAAAAAAAAAAAAAAPQ==.json": 6 * REWARD_MODIFIER,
    "SettingsTool-AAAAAAAAAAAAAAAAAAAAMQ==.json": 2 * REWARD_MODIFIER,
    "Shredder-AAAAAAAAAAAAAAAAAAAAGg==.json": 6 * REWARD_MODIFIER,
    "Smokestack-AAAAAAAAAAAAAAAAAAAAyg==.json": 5 * REWARD_MODIFIER,
    "SolarTowerBoiler-AAAAAAAAAAAAAAAAAAAAYg==.json": 5 * REWARD_MODIFIER,
    "SolderingStation-AAAAAAAAAAAAAAAAAAAAHA==.json": 6 * REWARD_MODIFIER,
    "SteamEngine-1WdjJYUsRMKgt4MYnlmM7A==.json": 6 * REWARD_MODIFIER,
    "SteelAnvil-AAAAAAAAAAAAAAAAAAAAuw==.json": 4 * REWARD_MODIFIER,
    "SteelFurnace-GOACXA8jRc-SMNzk2CsNUQ==.json": 4 * REWARD_MODIFIER,
    "StirlingEngine--OxoBRz7Spqm0rVUNxRVpA==.json": 4 * REWARD_MODIFIER,
    "StirlingSawmill-_qJt02i4ST2iccmkHudKCg==.json": 4 * REWARD_MODIFIER,
    "StorageDrawerKey-HTaQEgJ8QCWYNMB8n7Awug==.json": 2 * REWARD_MODIFIER,
    "StorageDrawers--7rSSbm6Q-qSPUPH2dapXA==.json": 3 * REWARD_MODIFIER,
    "StrandCaster-AAAAAAAAAAAAAAAAAAAAJA==.json": 5 * REWARD_MODIFIER,
    "StructureLooting-VoxsH2isSheNEKaJ3_Ikgg==.json": 3 * REWARD_MODIFIER,
    "TheEnd-iaDcxhSuSUi4Kp-PSHzjew==.json": 6 * REWARD_MODIFIER,
    "TheNether-FP0J62xtTreU3IFJHpFiDg==.json": 4 * REWARD_MODIFIER,
    "TrenchMask-AAAAAAAAAAAAAAAAAAAADA==.json": 3 * REWARD_MODIFIER,
    "TungstenReachers-daHRIdE8RNq4usNWqdv7fQ==.json": 4 * REWARD_MODIFIER,
    "WoodBurningGener-AAAAAAAAAAAAAAAAAAAAEw==.json": 3 * REWARD_MODIFIER,
}

NTM_OIL = {
    # NTM: Oil
    "AluminiumProcess-8Z2F5EPIRPGvasjKDWd4tA==.json": 8 * REWARD_MODIFIER,
    "Antimatter-AAAAAAAAAAAAAAAAAAAAGw==.json": 9 * REWARD_MODIFIER,
    "ArcFurnaceRORAut-xqZqIvJgRa25Gj5Qr25Wcg==.json": 7 * REWARD_MODIFIER,
    "AuxilaryCoolingT-AAAAAAAAAAAAAAAAAAAASA==.json": 6 * REWARD_MODIFIER,
    "Bakelite-AAAAAAAAAAAAAAAAAAAAQQ==.json": 6 * REWARD_MODIFIER,
    "Balefire-8OusetROQiyH-66QbewmNQ==.json": 9 * REWARD_MODIFIER,
    "BasicOilProcessi-AAAAAAAAAAAAAAAAAAAALw==.json": 8 * REWARD_MODIFIER,
    "BedrockOreExtrac-AAAAAAAAAAAAAAAAAAAALA==.json": 9 * REWARD_MODIFIER,
    "CatalyticCrackin-AAAAAAAAAAAAAAAAAAAAOw==.json": 9 * REWARD_MODIFIER,
    "Centrifuge-AAAAAAAAAAAAAAAAAAAAUg==.json": 7 * REWARD_MODIFIER,
    "CokerUnit-AAAAAAAAAAAAAAAAAAAARQ==.json": 7 * REWARD_MODIFIER,
    "Cyclotron-AAAAAAAAAAAAAAAAAAAA1g==.json": 10 * REWARD_MODIFIER,
    "Derrick-AAAAAAAAAAAAAAAAAAAAKw==.json": 7 * REWARD_MODIFIER,
    "Desh-AAAAAAAAAAAAAAAAAAAAQg==.json": 8 * REWARD_MODIFIER,
    "DeshAnvil-AAAAAAAAAAAAAAAAAAAAPA==.json": 7 * REWARD_MODIFIER,
    "DeshServoSet-AAAAAAAAAAAAAAAAAAAACw==.json": 6 * REWARD_MODIFIER,
    "ElectricArcFurna-AAAAAAAAAAAAAAAAAAAAHg==.json": 8 * REWARD_MODIFIER,
    "ElectricGroundwa-AAAAAAAAAAAAAAAAAAAAUw==.json": 6 * REWARD_MODIFIER,
    "ElectrolysisMach-AAAAAAAAAAAAAAAAAAAAzA==.json": 9 * REWARD_MODIFIER,
    "Fiberglass-mBnOQ4Z5TBiM29bD4GXBvQ==.json": 7 * REWARD_MODIFIER,
    "GeigerCounter-AAAAAAAAAAAAAAAAAAAAXw==.json": 6 * REWARD_MODIFIER,
    "HydraulicFrackin-AAAAAAAAAAAAAAAAAAAAUQ==.json": 10 * REWARD_MODIFIER,
    "ImpactDrill-AAAAAAAAAAAAAAAAAAAAKQ==.json": 6 * REWARD_MODIFIER,
    "IndustrialBoiler-AAAAAAAAAAAAAAAAAAAAPw==.json": 7 * REWARD_MODIFIER,
    "IndustrialLiquif-AAAAAAAAAAAAAAAAAAAAWA==.json": 7 * REWARD_MODIFIER,
    "IndustrialSolidi-AAAAAAAAAAAAAAAAAAAAVw==.json": 7 * REWARD_MODIFIER,
    "IndustrialSteamT-AAAAAAAAAAAAAAAAAAAARA==.json": 8 * REWARD_MODIFIER,
    "IntegratedCircui-AAAAAAAAAAAAAAAAAAAAIA==.json": 7 * REWARD_MODIFIER,
    "Jetpack-l6zSmdfhSw6aTqiJsNDiHg==.json": 6 * REWARD_MODIFIER,
    "LaunchPad-AAAAAAAAAAAAAAAAAAAAaw==.json": 8 * REWARD_MODIFIER,
    "M1TTYEnvironment-AAAAAAAAAAAAAAAAAAAADg==.json": 6 * REWARD_MODIFIER,
    "Microchip-Lc9HRIDwRZa0u-M3Ze6ZiQ==.json": 6 * REWARD_MODIFIER,
    "MilitaryGradeCir-AAAAAAAAAAAAAAAAAAAAIw==.json": 9 * REWARD_MODIFIER,
    "MiningLaser-zYS6AlyFSuuMUErAJqPcTg==.json": 9 * REWARD_MODIFIER,
    "OreAcidizer-AAAAAAAAAAAAAAAAAAAATw==.json": 9 * REWARD_MODIFIER,
    "Polymer-AAAAAAAAAAAAAAAAAAAAOg==.json": 6 * REWARD_MODIFIER,
    "PoweredDrill-UWNifpoeQfypMwfGniM40w==.json": 7 * REWARD_MODIFIER,
    "PrecisionAssembl-RACFotYCSpG7BihFhonkCA==.json": 9 * REWARD_MODIFIER,
    "Pumpjack-AAAAAAAAAAAAAAAAAAAATg==.json": 9 * REWARD_MODIFIER,
    "RedstoneFluidOve-ZTrtIRiyRO2J5jHQ4sroaQ==.json": 6 * REWARD_MODIFIER,
    "RedstoneOverRadi-gNS_yBDSS7uk2N7wr9PuYw==.json": 6 * REWARD_MODIFIER,
    "RefineryPower-AAAAAAAAAAAAAAAAAAAASw==.json": 8 * REWARD_MODIFIER,
    "Rubber-AAAAAAAAAAAAAAAAAAAAQA==.json": 6 * REWARD_MODIFIER,
    "SurveyScanner-AAAAAAAAAAAAAAAAAAAAYA==.json": 6 * REWARD_MODIFIER,
    "Tank-AAAAAAAAAAAAAAAAAAAAXg==.json": 4 * REWARD_MODIFIER,
    "Tantalum-AAAAAAAAAAAAAAAAAAAAiw==.json": 9 * REWARD_MODIFIER,
    "TransportDrones-AAAAAAAAAAAAAAAAAAAAdg==.json": 6 * REWARD_MODIFIER,
    "WeaponSteel-xADm9gLETmCgiS3amOTUcQ==.json": 8 * REWARD_MODIFIER,
}

NTM_BEDROCK = {
    # Bedrock Ore Processing
    "BedrockOreCrumbs-9UCrVSLuT663wp3s6K2AiQ==.json": 5 * REWARD_MODIFIER,
    "CentrifugedBedro-gfxplb02SayHVcvrjg5wQw==.json": 5 * REWARD_MODIFIER,
    "CleanedByproduct-8iNCagWWTD-29ECY764xsA==.json": 5 * REWARD_MODIFIER,
    "CleanedByproduct-QjmRsA1iSc2nvV0Fq5TVBg==.json": 5 * REWARD_MODIFIER,
    "DissolvedByprodu-lf0M379oRhK6Wtt1u1yzJg==.json": 5 * REWARD_MODIFIER,
    "DissolvedByprodu-XM83SUU1QpSooqGDwIm5vw==.json": 5 * REWARD_MODIFIER,
    "OreSlop-3cxFoKHGSHmwhLh4rTMHVg==.json": 5 * REWARD_MODIFIER,
    "PrimaryFractionA-E0QxGJQuRoiEUP7GO7PYdw==.json": 5 * REWARD_MODIFIER,
    "PrimaryFractionP-xbBcX3xpTDau2oGgLWMulA==.json": 5 * REWARD_MODIFIER,
    "RawBedrockOre-yuW7Zn_hSPiU8WZmFSY6lQ==.json": 5 * REWARD_MODIFIER,
    "RoastedBedrockOr-073YOAqUQpGxoX5HnU5VqA==.json": 5 * REWARD_MODIFIER,
    "RoastedCleanedBy-0jPPiKf3TsmtGbv9-y-FMQ==.json": 5 * REWARD_MODIFIER,
    "RoastedDissolved-7VfzcDkmQU2egBpwxRs4Fg==.json": 5 * REWARD_MODIFIER,
    "RoastedSulfuricB-BcWOg0FzQZSP3Z4OscWEUA==.json": 5 * REWARD_MODIFIER,
    "SecondBedrockOre-hvETQYjrT6iyC1DN019FRw==.json": 5 * REWARD_MODIFIER,
    "SecondBedrockOre-spY0QgAGTZmd3mNacRqDjQ==.json": 5 * REWARD_MODIFIER,
    "SeperatedCleanPr-rry4J7v5QNKgPYI9lxubRA==.json": 5 * REWARD_MODIFIER,
    "SolventWashedBed-iaXjcyplQc-ijtFP1Mvvfw==.json": 5 * REWARD_MODIFIER,
    "SulfuricByproduc-6pZz1HhdRIuMhK-Jey8oTA==.json": 5 * REWARD_MODIFIER,
    "SulfuricByproduc-DU8UbUuGR0moBP6vGSiH6w==.json": 5 * REWARD_MODIFIER,
    "Vitriol-lLZ1OeE6TlOFsiKNKu5p3Q==.json": 5 * REWARD_MODIFIER,
    "WashedCleanedByp-wNqkx13BS-SWoF9mDFzYsg==.json": 5 * REWARD_MODIFIER,
    "WashedDissolvedB-7ymDZyp4SqiscLJOSI2zGw==.json": 5 * REWARD_MODIFIER,
    "WashedSulfuricBy-CNzJA-nTSEi9nNMW9Pq9Fg==.json": 5 * REWARD_MODIFIER,
    "WaterWashedBedro-z95ToI2RQdSvpi_xIa2Tew==.json": 5 * REWARD_MODIFIER,
}

NTM_REACTOR = {
    # NTM: Reactors
    "AdditionalFusion-JpsvBP1yQsu-XtkeZegA6A==.json": 11 * REWARD_MODIFIER,
    "AdvancedOilProce-AAAAAAAAAAAAAAAAAAAAWw==.json": 11 * REWARD_MODIFIER,
    "Arsenic-tgpCNtEfScSyk-mdGhGxmQ==.json": 8 * REWARD_MODIFIER,
    "BigAssTank-AAAAAAAAAAAAAAAAAAAAjw==.json": 9 * REWARD_MODIFIER,
    "Bismuth-AAAAAAAAAAAAAAAAAAAAhw==.json": 9 * REWARD_MODIFIER,
    "BTX-AAAAAAAAAAAAAAAAAAAAng==.json": 9 * REWARD_MODIFIER,
    "Cadmium-9BjXTD5CSTOQ-_OroVdJmg==.json": 9 * REWARD_MODIFIER,
    "ChicagoPile-g8IVppPpTceY55PbNbceJQ==.json": 8 * REWARD_MODIFIER,
    "ChicagoPileAutom-M52T9-fTRi-0j18IHSGDVg==.json": 8 * REWARD_MODIFIER,
    "Chlorophyte-8oOJm62fRmKMu-HJni7Pwg==.json": 11 * REWARD_MODIFIER,
    "CMBSteel-AAAAAAAAAAAAAAAAAAAAug==.json": 11 * REWARD_MODIFIER,
    "CoolingTower-AAAAAAAAAAAAAAAAAAAAdQ==.json": 8 * REWARD_MODIFIER,
    "CrystallineFulle-AAAAAAAAAAAAAAAAAAAAww==.json": 12 * REWARD_MODIFIER,
    "DeshStamps-Wo-Z9nSKSH2ATqZXnY3CfA==.json": 8 * REWARD_MODIFIER,
    "DeuteriumExtract-teKlTYeLSNSvU4h8KGT0Ug==.json": 9 * REWARD_MODIFIER,
    "FELandSILEX-AAAAAAAAAAAAAAAAAAAAQw==.json": 11 * REWARD_MODIFIER,
    "FerricSchrabidat-AAAAAAAAAAAAAAAAAAAAuA==.json": 12 * REWARD_MODIFIER,
    "Ferrouranium-4jgH-_iMTDOer91Gj2FXiQ==.json": 8 * REWARD_MODIFIER,
    "FerrouraniumAnvi-AAAAAAAAAAAAAAAAAAAAbw==.json": 9 * REWARD_MODIFIER,
    "FissileMaterials-X6nUcp16QUqawLXQTqFTBw==.json": 9 * REWARD_MODIFIER,
    "FusionPower-WS2zNdGdTnmclQfj2ARCog==.json": 11 * REWARD_MODIFIER,
    "FusionReactor-8DXv-b9sRxalmY8yovSQuw==.json": 14 * REWARD_MODIFIER,
    "GasCentrifuge-2JMb-t2STTKM5sxV5Z7WOQ==.json": 9 * REWARD_MODIFIER,
    "GravityGun-AAAAAAAAAAAAAAAAAAAASg==.json": 9 * REWARD_MODIFIER,
    "HardPlasticPVCBa-AAAAAAAAAAAAAAAAAAAANA==.json": 9 * REWARD_MODIFIER,
    "HeatExchangingHe-rRJfZe74TXqpP-q2faX7bA==.json": 8 * REWARD_MODIFIER,
    "HeavyMagneticSto-AAAAAAAAAAAAAAAAAAAAkA==.json": 9 * REWARD_MODIFIER,
    "Helium4-wl8MTQpsQrG9gyaScmm2rg==.json": 11 * REWARD_MODIFIER,
    "HEVMarkIV-AAAAAAAAAAAAAAAAAAAAhA==.json": 9 * REWARD_MODIFIER,
    "HighPerformanceS-AAAAAAAAAAAAAAAAAAABPQ==.json": 9 * REWARD_MODIFIER,
    "HighPowerSteamCo-AAAAAAAAAAAAAAAAAAAA0Q==.json": 8 * REWARD_MODIFIER,
    "IonizedParticles-AAAAAAAAAAAAAAAAAAAAeA==.json": 11 * REWARD_MODIFIER,
    "LargeFactoryMult-8XHLo-wQRN28gu4AwCtHVQ==.json": 9 * REWARD_MODIFIER,
    "LeviathanSteamTu-AAAAAAAAAAAAAAAAAAAA1Q==.json": 11 * REWARD_MODIFIER,
    "LiquidatorMedal-AAAAAAAAAAAAAAAAAAAALQ==.json": 8 * REWARD_MODIFIER,
    "MagnetizedTungst-AAAAAAAAAAAAAAAAAAAArQ==.json": 11 * REWARD_MODIFIER,
    "NeutrinoLens-AAAAAAAAAAAAAAAAAAAAcA==.json": 9 * REWARD_MODIFIER,
    "NuclearBombs-sCe8OyBsQEeMrUpYXUn9Yw==.json": 9 * REWARD_MODIFIER,
    "NuclearFuelProce-7rFMNl3iSCOD-dpsKLAANQ==.json": 9 * REWARD_MODIFIER,
    "NuclearWasteDisp-eadYFbwuQTS39P9cW-D-Fw==.json": 8 * REWARD_MODIFIER,
    "PlasmaForge-LWQk4lZUTwqfXvCfPUbKXw==.json": 14 * REWARD_MODIFIER,
    "PUREX-g3S9-75wTGyQKmZaQTZl5Q==.json": 9 * REWARD_MODIFIER,
    "PWR-AAAAAAAAAAAAAAAAAAAACg==.json": 11 * REWARD_MODIFIER,
    "PWRpoweredSteelF-E6sLN7FkSrqAHohBC1W7gQ==.json": 8 * REWARD_MODIFIER,
    "PyrolysisOven-AAAAAAAAAAAAAAAAAAAANg==.json": 11 * REWARD_MODIFIER,
    "RadiationPowered-AAAAAAAAAAAAAAAAAAABeA==.json": 9 * REWARD_MODIFIER,
    "RBMK-AAAAAAAAAAAAAAAAAAAAAA==.json": 11 * REWARD_MODIFIER,
    "RBMKFuelProcessi-a0YRGBjSTGiD09r4LqD8EA==.json": 9 * REWARD_MODIFIER,
    "RedKey-NB6qs0xZSHaY5Sik2IoTxg==.json": 8 * REWARD_MODIFIER,
    "Reformate-AAAAAAAAAAAAAAAAAAAADQ==.json": 9 * REWARD_MODIFIER,
    "ReformateGas-AAAAAAAAAAAAAAAAAAAAPg==.json": 9 * REWARD_MODIFIER,
    "ResearchandBreed-AAAAAAAAAAAAAAAAAAAAiA==.json": 9 * REWARD_MODIFIER,
    "SatelliteLaunchi-ocylWycmSd6r-mvYENYGEw==.json": 11 * REWARD_MODIFIER,
    "Saturnite-AAAAAAAAAAAAAAAAAAAASQ==.json": 11 * REWARD_MODIFIER,
    "Schrabidium-AAAAAAAAAAAAAAAAAAAAVg==.json": 12 * REWARD_MODIFIER,
    "SolidMudBrick-AAAAAAAAAAAAAAAAAAAAuQ==.json": 9 * REWARD_MODIFIER,
    "SoyuzFG-AAAAAAAAAAAAAAAAAAAAZw==.json": 12 * REWARD_MODIFIER,
    "SpentFuelPoolDru-har7pEFcSRKNgIf4NgmcLA==.json": 8 * REWARD_MODIFIER,
    "Starmetal-AAAAAAAAAAAAAAAAAAAAJw==.json": 11 * REWARD_MODIFIER,
    "StarmetalPickaxe-8sIzBzykSPqskvhCp-Tsmw==.json": 9 * REWARD_MODIFIER,
    "Technetium99-iJiX7wxoSBmljc9tITqIqQ==.json": 8 * REWARD_MODIFIER,
    "TechnetiumCadmiu-AAAAAAAAAAAAAAAAAAAABg==.json": 9 * REWARD_MODIFIER,
    "TungstenCarbide-6GYfg5blTqC0-zrnYjON8w==.json": 9 * REWARD_MODIFIER,
    "Uranium238-CYtQLn_VSx2QTnLEwpMGOw==.json": 8 * REWARD_MODIFIER,
    "VacuumRefinery-AAAAAAAAAAAAAAAAAAAAkw==.json": 9 * REWARD_MODIFIER,
    "VersatileCircuit-AAAAAAAAAAAAAAAAAAAAMA==.json": 9 * REWARD_MODIFIER,
    "VersatileIntegra-AAAAAAAAAAAAAAAAAAAAKA==.json": 8 * REWARD_MODIFIER,
    "WatzPowerplant-AAAAAAAAAAAAAAAAAAAApg==.json": 12 * REWARD_MODIFIER,
    "WeldedTechnetium-AAAAAAAAAAAAAAAAAAAAjg==.json": 9 * REWARD_MODIFIER,
    "ZIRNOX-AAAAAAAAAAAAAAAAAAAAcg==.json": 9 * REWARD_MODIFIER,
}

NTM_PARTICLE = {
    # Particle Physics
    "AdditionalPartic-WONE5CQBTMCVbCuGUZqXpQ==.json": 2 * REWARD_MODIFIER,
    "Antischrabidium-q1BhemoLR6maeOr2F5qemw==.json": 12 * REWARD_MODIFIER,
    "ChickenNugget-DJQ2vE3LQ0e5pmnrwbNNkA==.json": 8 * REWARD_MODIFIER,
    "DarkMatter-8gdmudEZRRWDbmt_SgkifQ==.json": 12 * REWARD_MODIFIER,
    "DigammaLaserCrys-cDlOz30sQj6CDezzCvteDw==.json": 14 * REWARD_MODIFIER,
    "Dineutronium-gU8OT9pvSsaHXXvZZUn6sw==.json": 14 * REWARD_MODIFIER,
    "Euphemium-qeqHCCNDQYe89OHgI7zSNQ==.json": 14 * REWARD_MODIFIER,
    "ExposureChamber-1dJ5iJNbQ26XKKVjlR0Wsg==.json": 11 * REWARD_MODIFIER,
    "HiggsBoson-_1073ZttSUe0lJA38cUXeg==.json": 12 * REWARD_MODIFIER,
    "Muon-4dUQV5uHRiuVbPZQK-Tb-A==.json": 12 * REWARD_MODIFIER,
    "MurkyAnvil-UaqsY4yyStKS223fr9qVQg==.json": 14 * REWARD_MODIFIER,
    "MurkyWings-kKe1Ghz7R9W-kTBrBA8LLw==.json": 12 * REWARD_MODIFIER,
    "ParticleAccelera-hnI3TTSoSDytvFuil-40pg==.json": 11 * REWARD_MODIFIER,
    "ParticleAccelera-OCvBq3i-Q5CCZdpP4UKNKQ==.json": 11 * REWARD_MODIFIER,
    "ParticleAccelera-_nmJ1zrSQp22psctX6Uq2A==.json": 12 * REWARD_MODIFIER,
    "Sparkticle-zxEqSrCnTC-Ew950yepP3A==.json": 12 * REWARD_MODIFIER,
    "StrangeQuark-6gWNwAbqSwauVebymWHlKA==.json": 12 * REWARD_MODIFIER,
    "Tachyon-aVHAKgP-QQ-5HsJuMR5png==.json": 12 * REWARD_MODIFIER,
    "TheDigammaPartic-Vq7_230-TPKFYERt7zynAg==.json": 12 * REWARD_MODIFIER,
}

NTM_END = {
    # NTM: End Game
    "BallsOTron-k-HwTdGiQVmikRwAeg_fkQ==.json": 14 * REWARD_MODIFIER,
    "DFC-AAAAAAAAAAAAAAAAAAAANw==.json": 15 * REWARD_MODIFIER,
    "DineutroniumAnvi-AAAAAAAAAAAAAAAAAAABEA==.json": 14 * REWARD_MODIFIER,
    "DNTNanosuit-AAAAAAAAAAAAAAAAAAAANQ==.json": 15 * REWARD_MODIFIER,
    "FEnSU-AAAAAAAAAAAAAAAAAAABFg==.json": 15 * REWARD_MODIFIER,
    "GeraldtheConstru-AAAAAAAAAAAAAAAAAAABHw==.json": 15 * REWARD_MODIFIER,
    "ICF-AAAAAAAAAAAAAAAAAAAAig==.json": 15 * REWARD_MODIFIER,
    "ICFFuels-2BKf-swBTG61f8eVn9ynhw==.json": 14 * REWARD_MODIFIER,
    "ICFLaser-nqmqybchRzWn-T46-3vHmQ==.json": 14 * REWARD_MODIFIER,
    "ICFLaserTurbocha-hmwBFeuMQXiUrjE-WdD6-g==.json": 14 * REWARD_MODIFIER,
    "Magnetohydrodyna-BhhBylNPSPuvVJhPO93sdw==.json": 12 * REWARD_MODIFIER,
    "Osmiridium-AAAAAAAAAAAAAAAAAAABIQ==.json": 14 * REWARD_MODIFIER,
    "QuantumComputer-AAAAAAAAAAAAAAAAAAAAFg==.json": 12 * REWARD_MODIFIER,
    "QuantumProcessin-AAAAAAAAAAAAAAAAAAAAbQ==.json": 11 * REWARD_MODIFIER,
    "SchrabidiumHamme-AAAAAAAAAAAAAAAAAAABMA==.json": 15 * REWARD_MODIFIER,
    "SolidStateQuantu-AAAAAAAAAAAAAAAAAAAAGA==.json": 11 * REWARD_MODIFIER,
    "SparkLaserCrysta-AAAAAAAAAAAAAAAAAAABBA==.json": 14 * REWARD_MODIFIER,
    "SparkSingularity-AAAAAAAAAAAAAAAAAAABFQ==.json": 14 * REWARD_MODIFIER,
    "TheBookofBoxcars-AAAAAAAAAAAAAAAAAAABBQ==.json": 14 * REWARD_MODIFIER,
    "TheCrucible-AAAAAAAAAAAAAAAAAAABLw==.json": 15 * REWARD_MODIFIER,
    "UFO-q0Q4S7F-QlCzGWDkdOBMqw==.json": 14 * REWARD_MODIFIER,
    "WeldedOsmiridium-xYmNHPDAQkSwXHOow8--4g==.json": 14 * REWARD_MODIFIER,
    "YharoniteBillet-AAAAAAAAAAAAAAAAAAABKg==.json": 15 * REWARD_MODIFIER,
}

NTM_SPACE = {
    # NTM: Space
    "AirVent-jiPDr_h5RrqHUkzMYkuhpQ==.json": 9 * REWARD_MODIFIER,
    "AlkylationUnit-icj9Y8q0QiWjFk2g7dTnww==.json": 11 * REWARD_MODIFIER,
    "AtmosphericCompr-aZBaZGfVRHeXWmLqDHjuUw==.json": 11 * REWARD_MODIFIER,
    "AtmosphericScann-MqqnLpS-RLK6oNw12wzI7Q==.json": 8 * REWARD_MODIFIER,
    "BrineProcessing-WRZqHx4ZRia4S1zEWYFg-Q==.json": 9 * REWARD_MODIFIER,
    "CMBInsert-3fvMK3HASiaG4E0wg7MTrA==.json": 11 * REWARD_MODIFIER,
    "CO2Scrubber-mtikmzS9T1SXk8ysQvCckA==.json": 9 * REWARD_MODIFIER,
    "CryogenicDistill-7kkbpR6rS4CsUTUFQ5wd7g==.json": 11 * REWARD_MODIFIER,
    "DairyProcessingT-pEUat2aAT9az1GdhM3wvUA==.json": 9 * REWARD_MODIFIER,
    "Dres-rkMKa7TCT5u0jJsdH6TWnw==.json": 11 * REWARD_MODIFIER,
    "DriveProcessorTi-LKTbDe35Rte7XOisZoywOQ==.json": 11 * REWARD_MODIFIER,
    "DriveProcessorTi-QVJAi3JOR5in6VwMOEyL6w==.json": 11 * REWARD_MODIFIER,
    "DriveProcessorTi-VetSLWDYS8OTb7T4X9aAEw==.json": 9 * REWARD_MODIFIER,
    "DropPod-6YickkEnS--aDKBPtI6nrg==.json": 9 * REWARD_MODIFIER,
    "Duna--aAyklEkSHK7wGxEEzQJ9Q==.json": 11 * REWARD_MODIFIER,
    "DysonAnatmogenes-6k-JrbD-S8GO9PRRthWNRA==.json": 12 * REWARD_MODIFIER,
    "DysonSwarms-3WDOW4oRQoO6WN6291ZuNw==.json": 12 * REWARD_MODIFIER,
    "Eve-vWpv_FM5QYqYHsRsaNNwog==.json": 11 * REWARD_MODIFIER,
    "GalliumArsenide-DeOqQyXwQRq5RNcDa5l0ug==.json": 11 * REWARD_MODIFIER,
    "Hafnium-S0AQWdCYSeiUnhi2CmLszA==.json": 11 * REWARD_MODIFIER,
    "Hydrazine-M5NifoAtR2mnDAQpi9qfHg==.json": 9 * REWARD_MODIFIER,
    "Ike-KItM5UOCSNmCMNKnohadaQ==.json": 11 * REWARD_MODIFIER,
    "IndustrialGreenh-4HLGI5HyQtSw1G-iuwI0kg==.json": 9 * REWARD_MODIFIER,
    "Laythe-Tz9bzhSZQLGbAIEh4Zckbg==.json": 11 * REWARD_MODIFIER,
    "MagmaDrill-IaIkbc7YQeuiRONmPZSqdw==.json": 11 * REWARD_MODIFIER,
    "MicrogravityAlga-nfgxBE2jRE2InE-vMVEfRQ==.json": 11 * REWARD_MODIFIER,
    "MobileOrbitalSta-0PWQEKZ0QnWgh33WE1jS2A==.json": 11 * REWARD_MODIFIER,
    "Moho-yWu2LtytQjGg65tFXTo2ow==.json": 11 * REWARD_MODIFIER,
    "MunMinmus-SyNchvx5TpG6S7lF4jtiOA==.json": 9 * REWARD_MODIFIER,
    "OrbitalStation-NBDAp_kvThGG5C4yE0SiPA==.json": 11 * REWARD_MODIFIER,
    "OrbitalStationCo-sh6JGXJTRq2RSJp3UcQEeQ==.json": 9 * REWARD_MODIFIER,
    "RocketAssembling-w4uLB-JtTW-fCQA_qF6_ww==.json": 11 * REWARD_MODIFIER,
    "RocketPreparatio-XFyuo3SLQbmHtU7FcYdZ1g==.json": 8 * REWARD_MODIFIER,
    "RocketTransporte-utoxNiUARPOk7qRfnpN0Og==.json": 11 * REWARD_MODIFIER,
    "SolarPanel-xY1aWGAjTUGOWEhAdJ9kRw==.json": 8 * REWARD_MODIFIER,
    "SpaceEquipment-HvPzivF4SWWIDt5syO87xA==.json": 9 * REWARD_MODIFIER,
    "StainlessSteel-Q0hC3CjIR4GB7MtYPpxXgA==.json": 9 * REWARD_MODIFIER,
    "StardarandDriveP-ZPfHiJvPQIutgvhSROlbeQ==.json": 11 * REWARD_MODIFIER,
    "SteamRadiator-AB-0K2UoQF-7uQ9XiO8mqw==.json": 9 * REWARD_MODIFIER,
    "Tekto-tryLG0jySbGKMHzTFhvWOA==.json": 11 * REWARD_MODIFIER,
    "Teleporter-8j7JCxPeSaaBqlOTrRGtCg==.json": 11 * REWARD_MODIFIER,
    "VacuumSolderer-G3Em4SXiQee1Yu-Rd0yGaA==.json": 11 * REWARD_MODIFIER,
}

AE = {
    # AE2
    "AccelerationCard-g0hMKPOqRWKCKtSyhQtPsA==.json": 6 * REWARD_MODIFIER,
    "AE2Autocrafting-WUUIPZ-KQFCpsXAcpOxwqw==.json": 8 * REWARD_MODIFIER,
    "AE2Changes-AAAAAAAAAAAAAAAAAAAARg==.json": 2 * REWARD_MODIFIER,
    "CableFluix-AAAAAAAAAAAAAAAAAAAAeQ==.json": 6 * REWARD_MODIFIER,
    "CellWorkbench-_RJ-wMmFRWepNEgav4H2ZQ==.json": 5 * REWARD_MODIFIER,
    "CertusQuartzCrys-AAAAAAAAAAAAAAAAAAAARw==.json": 5 * REWARD_MODIFIER,
    "Charger-AAAAAAAAAAAAAAAAAAAAcw==.json": 6 * REWARD_MODIFIER,
    "CraftingCPU-ku71W0ZTQkOsyV4SQ0pPLA==.json": 8 * REWARD_MODIFIER,
    "CrystalGrowthAcc-AAAAAAAAAAAAAAAAAAAAcQ==.json": 6 * REWARD_MODIFIER,
    "CrystalGrowthCha-AAAAAAAAAAAAAAAAAAAATA==.json": 8 * REWARD_MODIFIER,
    "DenseMECable-gZL_U2jPTZe5oDt8FcJ2QQ==.json": 8 * REWARD_MODIFIER,
    "EnergyAcceptor-AAAAAAAAAAAAAAAAAAAAew==.json": 6 * REWARD_MODIFIER,
    "EnergyCell-Npl3Ifl9RvW8JZRicJaP2A==.json": 6 * REWARD_MODIFIER,
    "FluixCrystal-AAAAAAAAAAAAAAAAAAAAbA==.json": 5 * REWARD_MODIFIER,
    "InfinityBoosterC-EPrM6umbSw2e8c3-9XF9Wg==.json": 11 * REWARD_MODIFIER,
    "InterfaceP2P-Kcfw9puQQo-iehBFrlOp4g==.json": 8 * REWARD_MODIFIER,
    "MEBuses-AAAAAAAAAAAAAAAAAAAAgg==.json": 6 * REWARD_MODIFIER,
    "MEController-AAAAAAAAAAAAAAAAAAAAgA==.json": 9 * REWARD_MODIFIER,
    "MEDrive-AAAAAAAAAAAAAAAAAAAAfQ==.json": 8 * REWARD_MODIFIER,
    "MEInterface-AAAAAAAAAAAAAAAAAAAAfg==.json": 8 * REWARD_MODIFIER,
    "MEIOPort-4DM_-wpzThCM_KaSMIPmNA==.json": 6 * REWARD_MODIFIER,
    "MEPattern-lFAX1X73QMiTSYhQ3ozq_g==.json": 5 * REWARD_MODIFIER,
    "MEStorageBus-b4Wb4VV0RkSBMjTUJj8Idg==.json": 6 * REWARD_MODIFIER,
    "MEsubnetting-mGns1KltRda4-2iJggTT7w==.json": 5 * REWARD_MODIFIER,
    "METerminal-AAAAAAAAAAAAAAAAAAAAfA==.json": 6 * REWARD_MODIFIER,
    "ModifierCards-Qxy7Wf9WRnG-vIisndmV0g==.json": 5 * REWARD_MODIFIER,
    "MolecularAssembl-h0nPHR-TSQWbZhxIF9pAsA==.json": 8 * REWARD_MODIFIER,
    "NetworkTool-VE7Ty89_SMW45uAVQdD32g==.json": 5 * REWARD_MODIFIER,
    "NetworkVisualisa-mH0ic-3aRnOZ8FjP-n9qYw==.json": 5 * REWARD_MODIFIER,
    "OverflowVoidCard-xyHVMuUHQjSWbujlx1EMqw==.json": 6 * REWARD_MODIFIER,
    "P2P-Ig84-U5cRH-rxH76bIGE9A==.json": 8 * REWARD_MODIFIER,
    "P2PInterfacePara-1rIaClFKQbGXrdGi5-Eppg==.json": 8 * REWARD_MODIFIER,
    "P2PMENetworking-1bFqt414QEOwMpAVRSd3zg==.json": 8 * REWARD_MODIFIER,
    "PatternCapacityC-d4NudAjPT3G3f26jL0-SaA==.json": 6 * REWARD_MODIFIER,
    "QuantumNetworkBr-di_RfA7kSDGB_3iCgsfVaQ==.json": 12 * REWARD_MODIFIER,
    "SpatialIO-5PE7heWhR4qG8AcOcZ0VWQ==.json": 11 * REWARD_MODIFIER,
    "StorageComponent-AAAAAAAAAAAAAAAAAAAAYQ==.json": 6 * REWARD_MODIFIER,
    "WirelessConnecto-ReqBRrKdR2WFSp9ILSPk5w==.json": 9 * REWARD_MODIFIER,
    "WirelessCrafting-Iyj0bDhVRpCgzmAF4vP30A==.json": 9 * REWARD_MODIFIER,
    "WirelessTerminal-AAAAAAAAAAAAAAAAAAAAXQ==.json": 8 * REWARD_MODIFIER,
}

OPENCOMPUTERS = {
    # OpenComputers
    "CardBase-70KciiqATFCPJR3s6eoIMg==.json": 5 * REWARD_MODIFIER,
    "ComponentBuses-GWpBgrTUR6aiNelNbOLRWQ==.json": 5 * REWARD_MODIFIER,
    "Computer-zElcW5PDQwGOvbKnyroWEQ==.json": 8 * REWARD_MODIFIER,
    "ComputerCasings-XfkIHFJDRgSIyYD_F5b05g==.json": 6 * REWARD_MODIFIER,
    "ControlandArithm-ABODDDQgRrGXZdmgdHJ7Sg==.json": 6 * REWARD_MODIFIER,
    "CPUs--SW2UUweSLCzJBCGcIm3nw==.json": 6 * REWARD_MODIFIER,
    "ElectronicAssemb-7gCyEqlyTQqqnNxQ1cLt-A==.json": 9 * REWARD_MODIFIER,
    "FloppyDisksandDi-6wQAgmUHTxavpGXJvZVhmA==.json": 6 * REWARD_MODIFIER,
    "GraphicsCards-b14L2QcPTRiHysGkQNkTUQ==.json": 6 * REWARD_MODIFIER,
    "HardDrives-EdeL97xNTSmiLfPQpCJiow==.json": 6 * REWARD_MODIFIER,
    "InternetCard-1azNAAjWQLaNJLrVXT0W9w==.json": 6 * REWARD_MODIFIER,
    "Memory--0Jqqg9TRmCEikNnquKeuA==.json": 6 * REWARD_MODIFIER,
    "Microchips-5uHqD8E4RmWlcVca_5CJnQ==.json": 5 * REWARD_MODIFIER,
    "OCPower-l3OJx_niTg-UyYUoyOXYfg==.json": 5 * REWARD_MODIFIER,
    "PWRangler-DkfWKyKpReuU8BkzSMH3Xw==.json": 9 * REWARD_MODIFIER,
    "Screens-fS6P083FQGWwxARPYM4eaA==.json": 6 * REWARD_MODIFIER,
    "Servers-QFKT5L7RSrKQIz-qYhUsVg==.json": 8 * REWARD_MODIFIER,
    "Transistors-43PzmZVaTwS5ZaPt_fhugg==.json": 5 * REWARD_MODIFIER,
    "WelcometoOC-90cLqSYpT8OevVo7UEEaGA==.json": 2 * REWARD_MODIFIER,
    "WirelessNetworkC-8Bbui0CiRRm3hXTYH-ELpQ==.json": 8 * REWARD_MODIFIER,
}

BUILD = {
    # Building and Decorating
    "ArchitectureCraf-p7NNm2NvRgWz37LQO6yraw==.json": 3 * REWARD_MODIFIER,
    "AutoChisel-alOTKFb0Sbuzhkd7kUHfIQ==.json": 5 * REWARD_MODIFIER,
    "AutoChiselUpgrad-aTDQIHzUSVeuAt9EQuYEZQ==.json": 5 * REWARD_MODIFIER,
    "BetterBuildersWa-mPZ8D32cT5WrvlKuPNq90g==.json": 3 * REWARD_MODIFIER,
    "Chisel-TA6SPr3KTbKsgRFceNMZmA==.json": 3 * REWARD_MODIFIER,
    "LittleTiles-LUtxXey_T3q_oaUQWXpE7w==.json": 3 * REWARD_MODIFIER,
    "ModernMarkings-j9eLuGnhRVWn5uJS_KI5lg==.json": 3 * REWARD_MODIFIER,
    "Schematica-VyF-RUbsSuS8J2hbI5CIkw==.json": 3 * REWARD_MODIFIER,
    "SignPictures-wAu-q390TlKihyp-bEI2lw==.json": 3 * REWARD_MODIFIER,
    "Ztones-cJN-gv7iQzSfYZQVm1ZyVQ==.json": 3
}



REWARD_MAPPING = INTRO | NTM_EARLY | NTM_OIL | NTM_BEDROCK | NTM_REACTOR | NTM_PARTICLE | NTM_END | NTM_SPACE | AE | OPENCOMPUTERS | BUILD 