#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Mon Jun 22 18:22:15 EEST 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=12
allowUnknownShaders=false
shaderPack=ComplementaryReimagined_r5.7.1.zip
