name: Build Packs

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      modpack_name:
        required: true
        type: string
      build_java_version:
        required: true
        type: string

env:
  VERSION: ${{ inputs.version }}
  MODPACK_NAME: ${{ inputs.modpack_name }}
  BUILD_JAVA_VERSION: ${{ inputs.build_java_version }}

jobs:
  build-modrinth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Packwiz and Set Version
        uses: ./.github/actions/setup-packwiz
        with:
          version: ${{ env.VERSION }}

      - name: Inject GitHub Token for Packwiz
        run: |
          echo "[github]" > global-config.toml
          echo "token = \"${{ secrets.GITHUB_TOKEN }}\"" >> global-config.toml

      - name: Build Modrinth
        run: |
          packwiz refresh # just in case
          packwiz --config global-config.toml modrinth export -o "$MODPACK_NAME-modrinth.mrpack"

      - name: Upload Modrinth Artifact
        uses: actions/upload-artifact@v7
        with:
          name: modrinth-artifact
          path: ${{ env.MODPACK_NAME }}-modrinth.mrpack

  build-client:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Packwiz and Set Version
        uses: ./.github/actions/setup-packwiz
        with:
          version: ${{ env.VERSION }}

      - name: Setup Java
        uses: ./.github/actions/setup-java
        with:
          version: ${{ env.BUILD_JAVA_VERSION }}

      - name: Download Packwiz Installer Bootstrap
        uses: ./.github/actions/download-bootstrap

      - name: Build Client Zip (Pre-downloaded Client)
        run: |
          mkdir client
          cd client
          java -jar ../packwiz-installer-bootstrap.jar --no-gui --side client "file://${{ github.workspace }}/pack.toml"
          zip -rq "../$MODPACK_NAME-client.zip" ./*
          cd ..

      - name: Upload Client Artifact
        uses: actions/upload-artifact@v7
        with:
          name: client-artifact
          path: ${{ env.MODPACK_NAME }}-client.zip

  build-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Packwiz and Set Version
        uses: ./.github/actions/setup-packwiz
        with:
          version: ${{ env.VERSION }}

      - name: Setup Java
        uses: ./.github/actions/setup-java
        with:
          version: ${{ env.BUILD_JAVA_VERSION }}

      - name: Download Packwiz Installer Bootstrap
        uses: ./.github/actions/download-bootstrap

      - name: Build Server Zip
        run: |
          mkdir server-pack
          cd server-pack
          
          java -jar ../packwiz-installer-bootstrap.jar --no-gui --side server "file://${{ github.workspace }}/pack.toml"
          
          cp ../packwiz-installer-bootstrap.jar .
          
          # pterodactyl-cmd.txt is just for reference
          rsync -a \
            --include='eula.txt' \
            --include='java9args.txt' \
            --include='gc-args.txt' \
            --include='pretodactyl-cmd.txt' \
            --include='lwjgl3ify-*-forgePatches.jar' \
            --exclude '*' \
            server-template/ ./
          
          zip -rq "../$MODPACK_NAME-server.zip" ./*
          cd ..

      - name: Upload Server Artifact
        uses: actions/upload-artifact@v7
        with:
          name: server-artifact
          path: ${{ env.MODPACK_NAME }}-server.zip