name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (e.g. 1.0.0)"
        required: false
        default: "manual-build"

env:
  LAUNCHER_VERSION: "11.0.2-1"
  PORTABLE_JAVA_VERSION: "17"
  LWJGL3IFY_VERSION: "3.0.26"
  MODPACK_NAME: "103-ntm-space"
  INSTANCE_DIR: "103-ntm-space"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: "write"

    steps:
      - name: Set commit status - Pending
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state="pending" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -f description="Building release..." \
            -f context="Release Build"

      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Extract Version
        id: set_version_variable
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            VERSION="${{ github.event.release.tag_name }}"
            VERSION="${VERSION#v}"
          else
            VERSION="${{ github.event.inputs.version }}"
          fi
          
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set pack.toml version
        id: set_pack_version
        run: |
          sed -i "s/^version = .*/version = \"${{ env.VERSION }}\"/" pack.toml
          
          packwiz refresh

      - name: Inject GitHub Token for Packwiz
        run: |
          echo "[github]" > global-config.toml
          echo "token = \"${{ secrets.GITHUB_TOKEN }}\"" >> global-config.toml

      - name: Build Modrinth
        run: packwiz --config global-config.toml modrinth export -o "$MODPACK_NAME-modrinth.mrpack"

      - name: Download Packwiz Installer Bootstrap
        run: curl -L -s -o packwiz-installer-bootstrap.jar https://github.com/packwiz/packwiz-installer-bootstrap/releases/latest/download/packwiz-installer-bootstrap.jar

      - name: Build Client Zip (Pre-downloaded Client)
        run: |
          mkdir client
          cd client
          java -jar ../packwiz-installer-bootstrap.jar --no-gui --side client "file://${{ github.workspace }}/pack.toml"
          zip -rq "../$MODPACK_NAME-client.zip" ./*
          cd ..

      - name: Build Server Zip (Pre-downloaded Server)
        run: |
          mkdir server-pack
          cd server-pack
          java -jar ../packwiz-installer-bootstrap.jar --no-gui --side server "file://${{ github.workspace }}/pack.toml"
          zip -rq "../$MODPACK_NAME-server.zip" ./*
          cd ..

      - name: Build portable client - Windows
        run: |
          mkdir build-win
          cd build-win

          echo "Downloading Launcher..."
          curl -L -s -o launcher.zip "https://github.com/Diegiwg/PrismLauncher-Cracked/releases/download/$LAUNCHER_VERSION/PrismLauncher-Windows-MSVC-Portable-$LAUNCHER_VERSION.zip"
          mkdir -p launcher/
          unzip -q launcher.zip -d launcher
          rm launcher.zip

          echo "Downloading Java..."
          curl -L -s -o java.zip "https://api.adoptium.net/v3/binary/latest/$PORTABLE_JAVA_VERSION/ga/windows/x64/jre/hotspot/normal/eclipse"
          unzip -q java.zip
          mv jdk* launcher/java
          rm java.zip

          cp -r ../launcher-template/windows/* launcher/
          cp -r ../launcher-template/shared/* launcher/

          echo "Downloading LWJGL 3 patches..."
          curl -L -s -o lwjgl3.zip "https://github.com/GTNewHorizons/lwjgl3ify/releases/download/$LWJGL3IFY_VERSION/lwjgl3ify-$LWJGL3IFY_VERSION-multimc.zip"

          unzip -q lwjgl3.zip -d launcher/instances/$INSTANCE_DIR/
          rm lwjgl3.zip

          mkdir -p launcher/instances/$INSTANCE_DIR/minecraft
          cp ../packwiz-installer-bootstrap.jar launcher/instances/$INSTANCE_DIR/minecraft/

          echo "Compressing..."
          cd launcher
          zip -rq "../../$MODPACK_NAME-Windows.zip" ./*
          cd ../../

      - name: Build portable client - Linux
        run: |
          mkdir build-linux
          cd build-linux

          echo "Downloading Launcher..."
          curl -L -s -o launcher.tar.gz "https://github.com/Diegiwg/PrismLauncher-Cracked/releases/download/$LAUNCHER_VERSION/PrismLauncher-Linux-Qt6-Portable-$LAUNCHER_VERSION.tar.gz"
          mkdir -p launcher/
          tar -zxf launcher.tar.gz -C launcher
          rm launcher.tar.gz

          echo "Downloading Java..."
          curl -L -s -o java.tar.gz "https://api.adoptium.net/v3/binary/latest/$PORTABLE_JAVA_VERSION/ga/linux/x64/jre/hotspot/normal/eclipse"
          mkdir -p launcher/java
          tar -zxf java.tar.gz -C launcher/java --strip-components=1
          rm java.tar.gz

          cp -r ../launcher-template/linux/* launcher/
          cp -r ../launcher-template/shared/* launcher/

          echo "Downloading LWJGL 3 patches..."
          curl -L -s -o lwjgl3.zip "https://github.com/GTNewHorizons/lwjgl3ify/releases/download/$LWJGL3IFY_VERSION/lwjgl3ify-$LWJGL3IFY_VERSION-multimc.zip"

          unzip -q lwjgl3.zip -d launcher/instances/$INSTANCE_DIR/
          rm lwjgl3.zip

          mkdir -p launcher/instances/$INSTANCE_DIR/minecraft
          cp ../packwiz-installer-bootstrap.jar launcher/instances/$INSTANCE_DIR/minecraft/

          echo "Compressing..."
          cd launcher
          tar -czf "../../$MODPACK_NAME-Linux.tar.gz" ./*
          cd ../../

      - name: Build portable client - macOS
        run: |
          mkdir build-macos
          cd build-macos

          echo "Downloading Launcher..."
          curl -L -s -o launcher.zip "https://github.com/Diegiwg/PrismLauncher-Cracked/releases/download/$LAUNCHER_VERSION/PrismLauncher-macOS-$LAUNCHER_VERSION.zip"
          mkdir -p launcher/
          unzip -q launcher.zip -d launcher
          rm launcher.zip
          
          rm -rf launcher/__MACOSX
          
          APP_NAME="Prism Launcher"
          APP_DIR="$APP_NAME.app/Contents/MacOS"

          echo "Downloading Java..."
          curl -L -s -o java.tar.gz "https://api.adoptium.net/v3/binary/latest/$PORTABLE_JAVA_VERSION/ga/mac/x64/jre/hotspot/normal/eclipse"
          mkdir -p "launcher/$APP_DIR/java"
          tar -zxf java.tar.gz -C "launcher/$APP_DIR/java" --strip-components=1
          rm java.tar.gz

          cp -r ../launcher-template/macos/* "launcher/$APP_DIR/"
          cp -r ../launcher-template/shared/* "launcher/$APP_DIR/"

          echo "Downloading LWJGL 3 patches..."
          curl -L -s -o lwjgl3.zip "https://github.com/GTNewHorizons/lwjgl3ify/releases/download/$LWJGL3IFY_VERSION/lwjgl3ify-$LWJGL3IFY_VERSION-multimc.zip"

          unzip -q lwjgl3.zip -d "launcher/$APP_DIR/instances/$INSTANCE_DIR/"
          rm lwjgl3.zip

          mkdir -p "launcher/$APP_DIR/instances/$INSTANCE_DIR/minecraft"
          cp ../packwiz-installer-bootstrap.jar "launcher/$APP_DIR/instances/$INSTANCE_DIR/minecraft/"

          echo "Compressing..."
          cd launcher
          zip -rq "../../$MODPACK_NAME-macOS.zip" "$APP_NAME.app"
          cd ../../

      - name: Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} \
            $MODPACK_NAME-Windows.zip \
            $MODPACK_NAME-Linux.tar.gz \
            $MODPACK_NAME-macOS.zip \
            $MODPACK_NAME-modrinth.mrpack \
            $MODPACK_NAME-client.zip \
            $MODPACK_NAME-server.zip \
            --clobber

      - name: Upload Artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.VERSION }}
          path: |
            $MODPACK_NAME-Windows.zip
            $MODPACK_NAME-Linux.tar.gz
            $MODPACK_NAME-macOS.zip
            $MODPACK_NAME-modrinth.mrpack
            $MODPACK_NAME-client.zip
            $MODPACK_NAME-server.zip

      - name: Set commit status - Success
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST /repos/${{ github.repository }}/statuses/${{ github.sha }} \
          -f state='success' \
          -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
          -f description='Release build complete!' \
          -f context='Release Build'

      - name: Set commit status - Failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f state='failure' \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -f description='Release build failed.' \
            -f context='Release Build'