name: Build Pages

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  VERSION: ${{ inputs.version }}

jobs:
  build-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Packwiz and Set Version
        uses: ./.github/actions/setup-packwiz
        with:
          version: ${{ env.VERSION }}

      - name: Prepare GitHub Pages Site
        run: |
          mkdir _site
          
          rsync -a \
            --include='/pack.toml' \
            --include='/index.toml' \
            --include='/icon.png' \
            --include='/settings.rtg' \
            --include='/config/***' \
            --include='/modpack/***' \
            --include='/mods/***' \
            --include='/mods-optional/***' \
            --include='/scripts/***' \
            --include='/serverutilities/***' \
            --include='/server-template/***' \
            --exclude='*' \
            ./ _site/

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '_site'